from _typeshed import WriteableBuffer
from collections.abc import Iterator
from io import BufferedReader
from types import TracebackType
from typing import (
    Any,
    Optional,
    Type,
    Union,
)


class DecompressReader:
    """Adapts the decompressor reader API."""

    def __init__(
        self,
        fp: BufferedReader,
        decomp_factory: object,
        trailing_error: tuple = (),
        **decomp_args: Any,
    ) -> None:
        """Class initialization."""

        self._fp: BufferedReader
        self._eof: bool
        self._pos: int
        self._size: int
        self._decomp_factory: object
        self._decomp_args: dict[str, Any]
        self._decompressor: object
        self._trailing_error: tuple
        ...

    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...
    def readable(self) -> bool: ...
    def readline(self, size: int = -1) -> bytes: ...
    def readlines(self, hint: int = -1) -> list[bytes]: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...
    def truncate(self, size: Optional[int] = None) -> int: ...
    def writable(self) -> bool: ...
    def writelines(self, lines: list[bytes]) -> None: ...
    def write(self, b: Union[bytes, bytearray, memoryview]) -> int: ...
    def readinto(
        self, b: Union[WriteableBuffer, bytearray, memoryview]
    ) -> int: ...
    def read(self, size: int = -1) -> bytes: ...
    def readall(self) -> bytes: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def __enter__(self) -> DecompressReader: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> Optional[bool]: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __next__(self) -> bytes: ...
