# General
NO_COMPRESSION = 0
FAST_COMPRESSION = 1
DEFAULT_COMPRESSION = 6
HIGH_COMPRESSION = 9
ULTRA_COMPRESSION = 20

# Gzip
GZIP_VOID = NO_COMPRESSION
GZIP_FAST = FAST_COMPRESSION
GZIP_DEFAULT = DEFAULT_COMPRESSION
GZIP_HIGH = HIGH_COMPRESSION

# Lz4
LZ4_FAST = FAST_COMPRESSION
LZ4_DEFAULT = FAST_COMPRESSION
LZ4_BALANCED = HIGH_COMPRESSION
LZ4_HIGH = 16
LZ4_ULTRA = ULTRA_COMPRESSION

# Snappy
SNAPPY_DEFAULT = NO_COMPRESSION

# Zstd
ZSTD_FASTEST = -50
ZSTD_FAST = -5
ZSTD_DEFAULT = 3
ZSTD_BALANCED = 10
ZSTD_HIGH = 19
ZSTD_ULTRA = ULTRA_COMPRESSION
ZSTD_MAX = 22
